### PR TITLE
Property cuesheet.rems should be cuesheet.rem

### PR DESCRIPTION
**Pull request by Bludwarf**

### CODE REVIEW

**Comment by justlaputa** [comment]
hi @Bludwarf 
thanks for the PR, but this name is designed to match the cue sheet's command:
`REM ` -> `cuesheet.rem`

there is no reason to change it to plural form. If you have no other reason, I'm afraid I can not accept this PR.

**Comment by Bludwarf** [comment]
Hi @justlaputa 

You're right but I am just reusing what you defined in file [lib/cuesheet.js](https://github.com/justlaputa/cue-parser/blob/efa72995a4bf44bde7c7d77026960c9604202715/lib/cuesheet.js#L15) :

```
    this.rems = null;
```

This PR is intended to fix it and make it consistent.
If you think `this.rem` should be better, I can replace it in my PR.

**Comment by justlaputa** [comment]
hi @Bludwarf ,

  thanks for your check. I see, it's a hidden bug in `lib/cuesheet.js`, should change it
`this.rems` ==> `this.rem`

 can you change it in this PR?

**Comment by Bludwarf** [comment]
On my way ;)

**Comment by Bludwarf** [comment]
Done. Could you please close the issue when confirmed ?

**Comment by justlaputa** [comment]
Thanks very much 👍

**Pull request merged**
