### PR TITLE
Support EAC and XLD CUE's splitting one file per track

### PR DESCRIPTION
**Pull request by Borewit**
ToDo:

- [x] Fix unit test

### CODE REVIEW

**Comment by Borewit** [comment]
I think it is ready now for merging @justlaputa.

**Comment by justlaputa** [comment]
thanks I will check it.

**Comment by Borewit** [comment]
Do you think you have time to review my PR's anywhere soon @justlaputa?

**Comment by justlaputa** [comment]
yes I will take a look.
sorry was a little busy to check github.

**Comment by Borewit** [comment]
If offer you to take over the maintenance of cue-parser. Other projects I maintain: [music-metadata](https://github.com/Borewit/music-metadata),  [music-metadata-browser](https://github.com/Borewit/music-metadata-browser), [musicbrainz-api](https://github.com/Borewit/musicbrainz-api) and [a few more](https://github.com/Borewit?tab=repositories). I contribute to [webtorrent-desktop](https://github.com/webtorrent/webtorrent-desktop) and [file-type](https://github.com/sindresorhus/file-type).

A cue sheet parser would be a nice to add to the audio file parser components. I think a good parser (able to parse all [cue sheets](https://kodi.wiki/view/Cue_sheets)) is lacking. I think your parser is the most suitable to use as a starting point.

**Comment by justlaputa** [comment]
Hi @Borewit thanks very much for your offer, I'd like to give maintenance to you. Your repos looks awesome, and I like the webtorrent project.

sorry I couldn't find more time to check your PRs. Let me add you to contributors.

**Comment by Borewit** [comment]
Great, I am traveling at the moment. Within a few days I will get started. Can you please give me release permissions on NPM accordingly? My username is the same on NPM.

**Comment by Borewit** [comment]
Can you please reply @justlaputa, I would like to get started. I am more then happy to continue your work and to keep you involved, but I want to be able to work independent. Depending if you plan to participate yourself, great, grant me sufficient access. If you expect I will do all the work, no problem neither, I still hope you keep being a bit involved, but please transfer ownership of the NPM module in that case.

I hope you understand, I don't want to risk spending a lot of effort on the project and to be stuck. If you want to have a chat, you can find me [here](https://discord.gg/MHr4MtX).

**Comment by justlaputa** [comment]
hi @Borewit, yes I will grant the NPM permission. Thanks I will get more involved on this.

**Comment by justlaputa** [comment]
Done, please check npm if it works.

**Comment by Borewit** [comment]
> Done, please check npm if it works.

I think it's good.

Are you open to moving to TypeScript and/or updating the ECMAScript version?

**Comment by justlaputa** [comment]
yes, I would like to move to TS, if you are up to it that's great!

**Comment by Borewit** [comment]
Merged via #15

**Pull request closed without merging**
