### PR TITLE
add typescript declaration files

### PR DESCRIPTION
**Pull request by lightrabbit**

### CODE REVIEW

**Comment by justlaputa** [comment]
hi, thanks for the PR.
can you tell me what you want to add?

**Comment by lightrabbit** [comment]
Sorry for my mistakes.
I plan to add a TypeScript declaration file for this package.
The declaration file allows many IDEs (such as the Visual Studio Code) to provide automatic completion information for this package.
This speeds up development.

**Comment by Borewit** [comment]
Type definition will be included [by migrating to TypeScript](https://github.com/justlaputa/cue-parser/issues/16)

**Comment by Borewit** [comment]
Superseded by #18.
I would like to here your feedback @lightrabbit

**Pull request closed without merging**
