### PR TITLE
Prevent execution in test-description

### PR DESCRIPTION
**Pull request by Borewit**

### CODE REVIEW

**Comment by Borewit** [comment]
Hmm, I just noticed I did a very ugly job scoping the parse result.

Do you want to stick with the var's or move on using ES6+ block scoped const and let?

**Comment by justlaputa** [comment]
hi @Borewit, thanks for the PR.
I'm not very sure the purpose of this PR. Is this a bug or something wrong with the test code?

**Comment by Borewit** [comment]
The purpose of this PR is to move critical code from the _suite callbacks_ like the Mocha _describe_ call-back function to the _test_ callbacks, like _it_.

Mocha basically discovers which test should be executed first (calling the _suite callbacks_), building up this nice tree. After that it will run the actual tests.

However, in one of the  _describe_ call-back function, the actual parsing was done. If the parsing would fail, Mocha is not going to be able to tell you in which tests this was, because it already crashed before getting in to the test phase.

**Comment by Borewit** [comment]
I checked my changes again, and it fixes the issue. The file-change summary looked a bit odd due to the lines missing between the 2 updated code fragments (the actual fix & and the code style fix adding a missing `;`)

**Comment by justlaputa** [comment]
ah, I see. Thanks for your explanation.
Can we move that to the mocha hook function like `before() {...}`, so it will be executed before all tests, but not inside the _describe_ callback.

**Comment by Borewit** [comment]
> Can we move that to the mocha hook function `before()`

I think the `beforeEach`, like you have done with mos tests, is fine, if it fails it would probably have an effect on the entire suite, but that I don't think that is bad thing.

Or combine more in a single test, but you would loose granularity on your test descriptions. I have been struggling with that as well. Using a assertions framework which allows to descriptions can compensate a it, but you will only see those descriptions if it the assertion fails.

**Pull request merged**
